### ISSUE TITLE
Demangling for non _ZN prefixed symbols

### ISSUE THREAD

**Issue by bbqsrc** [alexcrichton/rustc-demangle#12]
One symbol that I am getting back from the `backtrace` crate is `_$LT$F$u20$as$u20$alloc..boxed..FnBox$LT$A$GT$$GT$::call_box::h292cc87894ba716c`. The demangle function does not currently handle this kind of output.

Is this something this crate could handle, or is there another that is suitable?

**Comment by alexcrichton** [comment]
Hm interesting! It looks like some demangling succeeded but not all of it (there's `::` characters in the symbol). Do you know what the original symbol was?

**Comment by bbqsrc** [comment]
That is the format in which I get the symbol string. Perhaps `backtrace` uses demangle itself?

**Comment by alexcrichton** [comment]
Is this example gist-able to see where it's getting printed?

**Comment by jsgf** [comment]
That looks like its been through a C++ demangler first.

**Comment by alexcrichton** [comment]
Indeed seems like a stale issue now!
