### ISSUE TITLE
Provide C interface

### ISSUE THREAD

**Issue by zokier** [alexcrichton/rustc-demangle#13]
[Bloaty](https://github.com/google/bloaty/) has a use for Rust name demangling (see [bloaty#110](https://github.com/google/bloaty/issues/110)). Bloaty being C++ application we'd need to have a C interface to be able use rustc-demangle for that purpose.

I made quick wrapper ([zokier/rustc-demangle-clib](https://github.com/zokier/rust-demangle-clib)) but I think it is something that would make sense to have in-tree here.

The exact form of the interface can be discussed further, that wrapper has been made solely for the needs of bloaty.

If agreed, I can polish the the code (add tests and docs) and submit it as PR here.

**Comment by zokier** [comment]
For further context, bloaty is a elf/mach file size analyzer, which I think would be useful for the wider Rust community if it were able to demangle Rust symbols.

**Comment by alexcrichton** [comment]
I'd be totally down for supporting this! I think this library would make a great candidate for a C interface :)

If you want to send a PR I'd be more than willing to help take a look and see how we can land it

**Comment by michaelwoerister** [comment]
@zokier & @alexcrichton Is there anything blocking this PR? What would be needed to push it over the finish line?

**Comment by alexcrichton** [comment]
Nah nothing blocking, just never got around to finishing it I think!
