### ISSUE TITLE
Error: unable to get packages from source

### ISSUE THREAD

**Issue by harishbm34** [alexcrichton/rustc-demangle#21]
Trying to build docker image using : alpine-edge

**Getting the below error :** 

Caused by:
  failed to parse manifest at `/root/.cargo/registry/src/github.com-1ecc6299db9ec823/rustc-demangle-0.1.10/Cargo.toml`

Caused by:
  feature `rename-dependency` is required

this Cargo does not support nightly features, but if you
switch to nightly channel you can add
`cargo-features = ["rename-dependency"]` to enable this feature
make[1]: Leaving directory '/go/src/github.com/gallactic/sputnikvm-ffi/c'
make[1]: *** [Makefile:11: build] Error 101
make: *** [Makefile:34: deps] Error 2

**Comment by alexcrichton** [comment]
I've published 0.1.11 to fix this

**Comment by lacabra** [comment]
I'm getting this very same issue in version `0.1.14`:
```
error: unable to get packages from source                                                                                                                           

Caused by:
  failed to parse manifest at `/root/.cargo/registry/src/github.com-1ecc6299db9ec823/rustc-demangle-0.1.14/Cargo.toml`

Caused by:
  feature `rename-dependency` is required

consider adding `cargo-features = ["rename-dependency"]` to the manifest
```

I am working on a project that requires re-building from sources daily, and it worked fine for months, until 3 days ago when `0.1.14` was released. Is it possible that something broke then?

**Comment by alexcrichton** [comment]
This crate now requires rustc 1.31.0+

**Comment by lacabra** [comment]
Thanks @alexcrichton. My version of rust is:
```
# rustc --version
rustc 1.31.0-nightly (fc403ad98 2018-09-30)
```
Isn't this enough?

**Comment by alexcrichton** [comment]
Given that you're getting an error, I don't think so, you may need a later nightly.
