### ISSUE TITLE
Add never type support

### ISSUE THREAD

**Issue by quininer** [alexcrichton/rustc-demangle#22]
`_ZN88_$LT$core..result..Result$LT$$u21$$C$$u20$E$GT$$u20$as$u20$std..process..Termination$GT$6report17hfc41d0da4a40b3e8E` can't be correct demangle.

https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=3fb17941fa424e80575eead2314b0407

**Comment by alexcrichton** [comment]
Thanks for the report!
