### ISSUE TITLE
0.1.14 broke compatibility with rust 1.30.0

### ISSUE THREAD

**Issue by LegNeato** [alexcrichton/rustc-demangle#25]
https://github.com/alexcrichton/rustc-demangle/commit/d74ae4b56ab6459f05afcb22c32371033cac75ff appears to have broken compatibility with rust 1.30.0. In [`juniper`](https://github.com/graphql-rust/juniper/) we see a new [CI failure](https://dev.azure.com/graphql-rust/GraphQL%20Rust/_build/results?buildId=243):

```
Downloading rustc-demangle v0.1.14
error: unable to get packages from source

Caused by:
  failed to parse manifest at `/Users/vsts/.cargo/registry/src/github.com-1ecc6299db9ec823/rustc-demangle-0.1.14/Cargo.toml`

Caused by:
  feature `rename-dependency` is required

this Cargo does not support nightly features, but if you
switch to nightly channel you can add
`cargo-features = ["rename-dependency"]` to enable this feature
```

Note that `juniper` is not using `rustc-demangle` directly.

I couldn't find anything that said this was intentional so I wanted to flag if it wasn't.

**Comment by alexcrichton** [comment]
Thanks for the report! This crate however requires 1.31.0 now
