### ISSUE TITLE
release new version including deprecated code cleanup

### ISSUE THREAD

**Issue by programmerjake** [alexcrichton/rustc-demangle#35]
Publish a version including all the improvements from #32

**Comment by alexcrichton** [comment]
Thanks for the report, but can you elaborate why a new release needs to be made? I don't think there's any functional changes to publish?

**Comment by programmerjake** [comment]
Not functional changes, but UI improvements for those who build in verbose mode so there isn't a pile of warnings in the build log.

I'm building in verbose mode because I am building LLVM from a build.rs and want some progress indicators.

**Comment by alexcrichton** [comment]
Ah ok, thanks for the clarification. I'm gonna close this in that case since I don't think a release is warranted, and I wouldn't recommend watching the extremely verbose logs where you get warnings for all your dependencies, because it ends up being a never-ending battle trying to be warning free.

**Comment by programmerjake** [comment]
ok, makes sense.
