### ISSUE TITLE
rustc_demangle doesn't work

### ISSUE THREAD

**Issue by milianw** [alexcrichton/rustc-demangle#38]
I'm trying to consume rustc_demangle via the release .so from hotspot (a UI for linux perf). For starters, I've looked into a perf file for a rust symbol, and found this e.g.:

```
_$LT$cargo..core..registry..PackageRegistry$u20$as$u20$cargo..core..registry..Registry$GT$::query::_$u7b$$u7b$closure$u7d$$u7d$::hbf90540c90f82f91
```

But when I now do this:

```
#include <cstdio>
#include <rustc_demangle.h>

int main(int argc, char** argv)
{
    size_t BUF_SIZE = 1024;
    char buffer[BUF_SIZE] = {};
    for (int i = 1; i < argc; ++i) {
        if (!rustc_demangle(argv[i], buffer, BUF_SIZE)) {
            fprintf(stderr, "failed to demangle: %s\n", argv[i]);
        } else {
            fprintf(stderr, "%s -> %s\n", argv[i], buffer);
        }
    }
    return 0;
}
```

compiled via:

```
g++ test.cpp -I /home/milian/projects/playground/rustc-demangle/crates/capi/include -l /home/milian/projects/playground/rustc-demangle/target/release/librustc_demangle.so
```

then I only see "failed to demangle" for the rust symbols I throw at it (like the one specified above).

```
$ git describe
0.1.7-45-gc4e3ab0
```

what am I missing?

**Comment by alexcrichton** [comment]
Thanks for the report! The problem here I believe is that the symbol has been partially demangled, and this library currently only supports demangling raw symbols. The presence of `::` shows that it's likely a C++ demangler has already gone first at attempting to demangle that.

**Comment by milianw** [comment]
Doh! thank you, that is indeed the problem.

Is there a way to easily check whether a mangled name is a rust symbol or not? The "real" mangled symbols e.g. look like a C++ symbol when you just look at the leading `_Z`. Is there any reliable way to distinguish that? I'm thinking about checking for the trailing `17h` followed by the 16 hex digits and then a trailing `E`?

```
_ZN11rustc_infer6traits28normalize_param_env_or_error17h6c20681ff348eb87E
_ZN12rustc_typeck5check6_match45_$LT$impl$u20$rustc_typeck..check..FnCtxt$GT$11check_match17h370c027c27cc9e6dE
```

**Comment by alexcrichton** [comment]
Currently there's no great way with those symbols to tell that they're Rust symbols. There's a new symbol mangling scheme which is clearly demarcated as a Rust symbol, but that's not turned on by default yet. Otherwise, yeah, I'd recommend looking for the 16 hex digits at the end since I think only rustc does that right now.

**Comment by milianw** [comment]
thank you
