### ISSUE TITLE
Publish `rustc-demangle-capi` on crates.io

### ISSUE THREAD

**Issue by maurer** [alexcrichton/rustc-demangle#44]
Right now, `rustc-demangle-capi` only exists as a subdirectory of this repository. In Android, we've been using crates.io as our primary source of third party packages, and it would be nice for `rustc-demangle` to not be an exception.

I could upload it myself, but I figured that Crichton should probably own the package.

For other users, making this crate available would also make it easier to pull into their builds, whether through a `rules_rust` style build in Bazel or by invoking `cargo` to build the `.a` or `.so` they need from crates.io or a cargo vendor directory. It also makes sense given https://github.com/rust-lang/rfcs/pull/3028 which makes these possibly useful artifacts to a Cargo build.

**Comment by alexcrichton** [comment]
Sure thing! Published now

**Comment by krtab** [comment]
Hi!

I am a bit confused with regards to two points:
  
  1. What does this change add/provides?
  2. What is now the preferred way to package the C API of rustc-demangle? I'm [packaging](https://github.com/krtab/rustc-demangle-archpkg/blob/6581223061b9e102be6a1c2fe85414e05774f257/PKGBUILD) it for the AUR and I'm not sure whether or not I should switch to this new crate.
  
Thanks

**Comment by alexcrichton** [comment]
This published the crate on crates.io. You can use it if you'd like, you also don't have to use it. I don't know enough about packaging to advise how to package this.

**Comment by krtab** [comment]
Thanks for the answer. :)
