### ISSUE TITLE
Fail to demangle some symbols with v0 mangling syntax

### ISSUE THREAD

**Issue by EFanZh** [alexcrichton/rustc-demangle#45]
Compile the following program with `-Zsymbol-mangling-version=v0` flag:

```rust
fn main() {
    let _: Box<dyn Fn(&i32)> = Box::new(|_| {});
}
```

There are some symbols in the generated binary that start with `_R` but won’t demangle. Here is an example:

```
_RNvMs1_NtNtCs4RZURTQcbNt_4core3ptr6uniqueINtB5_6UniqueDG_INtNtNtB9_3ops8function2FnTRL0_lEEG_p6OutputuEL_E6as_refCs64Hs8MuYH5P_13mangled_names
```

After removing the second `G_` substring, this one does demangle to `<core[38bc23ee7739a169]::ptr::unique::Unique<dyn for<'a> core[38bc23ee7739a169]::ops::function::Fn<(&'a i32,), Output = ()>>>::as_ref`:

```
_RNvMs1_NtNtCs4RZURTQcbNt_4core3ptr6uniqueINtB5_6UniqueDG_INtNtNtB9_3ops8function2FnTRL0_lEEp6OutputuEL_E6as_refCs64Hs8MuYH5P_13mangled_names
```

**Comment by EFanZh** [comment]
Maybe related: https://github.com/rust-lang/rust/issues/83611.

**Comment by michaelwoerister** [comment]
Is this still an issue?

**Comment by EFanZh** [comment]
I think it is OK now.
